apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app

resources:
  - ../../base

images:
  - name: acr_login_server/web
    newName: acr_login_server/web
    newTag: latest

patches:
  - target:
      kind: ServiceAccount
      name: workload-sa
    patch: |
      - op: replace
        path: /metadata/annotations/azure.workload.identity~1client-id
        value: workload_identity_client_id
